// Select all navigation links
const navLinks = document.querySelectorAll('nav ul li a');

// Add event listener to each navigation link
navLinks.forEach((link) => {
  link.addEventListener('click', (e) => {
      try {
            // Prevent default link behavior
                  e.preventDefault();

                        // Get the href attribute of the link
                              const href = link.getAttribute('href');

                                    // Check if the link is an anchor link
                                          if (href.startsWith('#')) {
                                                  // Get the target element
                                                          const targetElement = document.querySelector(href);

                                                                  // Check if the target element exists
                                                                          if (targetElement) {
                                                                                    // Scroll to the target element
                                                                                              targetElement.scrollIntoView({ behavior: 'smooth' });
                                                                                                      } else {
                                                                                                                console.error(`Target element not found for ${href}`);
                                                                                                                        }
                                                                                                                              } else {
                                                                                                                                      // Handle external links
                                                                                                                                              window.location.href = href;
                                                                                                                                                    }
                                                                                                                                                        } catch (error) {
                                                                                                                                                              console.error(error);
                                                                                                                                                                  }
                                                                                                                                                                    });
                                                                                                                                                                    });

                                                                                                                                                                    // Select the "Shop Now" button
                                                                                                                                                                    const shopNowButton = document.querySelector('button');

                                                                                                                                                                    // Add event listener to the "Shop Now" button
                                                                                                                                                                    if (shopNowButton) {
                                                                                                                                                                      shopNowButton.addEventListener('click', () => {
                                                                                                                                                                          try {
                                                                                                                                                                                // Get the products section
                                                                                                                                                                                      const productsSection = document.querySelector('#products');

                                                                                                                                                                                            // Check if the products section exists
                                                                                                                                                                                                  if (productsSection) {
                                                                                                                                                                                                          // Scroll to the products section
                                                                                                                                                                                                                  productsSection.scrollIntoView({ behavior: 'smooth' });
                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                console.error('Products section not found');
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                console.error(error);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                        console.error('Shop Now button not found');
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        // Dynamic copyright year update
                                                                                                                                                                                                                                                        const footer = document.querySelector('footer p');

                                                                                                                                                                                                                                                        if (footer) {
                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                              // Update the copyright year
                                                                                                                                                                                                                                                                  footer.innerHTML = `&copy; ${new Date().getFullYear()} Tom and Jelly Baby Store`;
                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                        console.error(error);
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                            console.error('Footer element not found');
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                            // Product grid functionality
                                                                                                                                                                                                                                                                            const productGrid = document.querySelector('.product-grid');
                                                                                                                                                                                                                                                                            const products = [
                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                  image: 'product1.jpg',
                                                                                                                                                                                                                                                                                      name: 'Product 1',
                                                                                                                                                                                                                                                                                          price: 'UGX 50,000'
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                  image: 'product2.jpg',
                                                                                                                                                                                                                                                                                                      name: 'Product 2',
                                                                                                                                                                                                                                                                                                          price: 'UGX 30,000'
                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                              // Add more products here
                                                                                                                                                                                                                                                                                                              ];

                                                                                                                                                                                                                                                                                                              if (productGrid) {
                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                    // Create product cards
                                                                                                                                                                                                                                                                                                                        products.forEach((product) => {
                                                                                                                                                                                                                                                                                                                              const productCard = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                    productCard.classList.add('product');
                                                                                                                                                                                                                                                                                                                                          productCard.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                  <img src="${product.image}" alt="${product.name}">
                                                                                                                                                                                                                                                                                                                                                          <h3>${product.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                  <p>${product.price}</p>
                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                              productGrid.appendChild(productCard);
                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                        console.error(error);
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                            console.error('Product grid element not found');
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                            // Contact form functionality
                                                                                                                                                                                                                                                                                                                                                                                            const contactForm = document.querySelector('#contact form');

                                                                                                                                                                                                                                                                                                                                                                                            if (contactForm) {
                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                  // Add event listener to the contact form
                                                                                                                                                                                                                                                                                                                                                                                                      contactForm.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                            e.preventDefault();

                                                                                                                                                                                                                                                                                                                                                                                                                  // Get the form fields
                                                                                                                                                                                                                                                                                                                                                                                                                        const name = contactForm.querySelector('input[name="name"]').value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                              const email = contactForm.querySelector('input[name="email"]').value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                    const message = contactForm.querySelector('textarea[name="message"]').value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                          // Validate the form fields
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (name && email && message) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Handle form submission logic here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Name: ${name}, Email: ${email}, Message: ${message}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Send message to WhatsApp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const whatsappLink = `https://wa.me/256787848965?text=Name:%20${name}%0AEmail:%20${email}%0AMessage:%20${message}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.open(whatsappLink, '_blank');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('Please fill out all fields');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Contact form element not found');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Add WhatsApp link to contact section
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const whatsappLink = document.querySelector('#contact ul li a[href*="whatsapp"]');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      